import { useState } from "react";
import { LETTERS } from "@/lib/earthverse-data";
import { SectionHeader } from "./ClimateLegacyScore";

export function LetterFromFuture() {
  const [tone, setTone] = useState<"positive" | "negative">("positive");
  const letter = LETTERS[tone];

  return (
    <section id="letter" className="relative py-20">
      <div className="mx-auto max-w-7xl px-4">
        <SectionHeader
          eyebrow="Feature 02 · AI Future Letter Generator"
          title={<>A letter, hand-written from <span className="text-aurora">2050</span>.</>}
          desc="Generated from your behavioral signature. Toggle between two futures branching from today's choices."
        />

        <div className="mt-10 flex flex-wrap items-center gap-2">
          {(["positive", "negative"] as const).map((t) => (
            <button
              key={t}
              onClick={() => setTone(t)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
                tone === t
                  ? "bg-[var(--gradient-cyber)] text-primary-foreground glow-ring"
                  : "glass text-muted-foreground hover:text-foreground"
              }`}
            >
              {t === "positive" ? "✨ Regenerative future" : "⚠️ Cautionary future"}
            </button>
          ))}
          <div className="ml-auto hidden sm:flex items-center gap-2 text-xs font-mono text-muted-foreground">
            <span className="h-1.5 w-1.5 rounded-full bg-violet-400 animate-pulse" />
            Generated by EarthVerse Narrative Engine
          </div>
        </div>

        <div className="mt-6 glass-strong rounded-3xl overflow-hidden relative">
          {/* Document chrome */}
          <div className="flex items-center gap-3 px-6 py-3 border-b border-white/10 bg-white/5">
            <div className="flex gap-1.5">
              <span className="h-2.5 w-2.5 rounded-full bg-rose-400/70" />
              <span className="h-2.5 w-2.5 rounded-full bg-amber-400/70" />
              <span className="h-2.5 w-2.5 rounded-full bg-emerald-400/70" />
            </div>
            <div className="font-mono text-xs text-muted-foreground truncate">
              earthverse://archive/letters/{tone}/aarav.2050.txt
            </div>
            <div className="ml-auto text-[10px] font-mono uppercase tracking-wider text-muted-foreground hidden sm:block">
              CLASSIFIED · TEMPORAL DELIVERY
            </div>
          </div>

          <div className="grid lg:grid-cols-[1fr_2fr] gap-0">
            {/* Side panel */}
            <div className="p-7 border-b lg:border-b-0 lg:border-r border-white/10 bg-white/[0.02]">
              <div className="text-xs font-mono uppercase tracking-wider text-muted-foreground">
                From
              </div>
              <div className="mt-1 font-display text-lg">{letter.from}</div>

              <div className="mt-6 text-xs font-mono uppercase tracking-wider text-muted-foreground">
                Subject
              </div>
              <div className="mt-1 font-display text-xl leading-snug text-aurora">
                {letter.headline}
              </div>

              <div className="mt-8 space-y-3 text-xs">
                {[
                  ["Sent from", "April 14, 2050"],
                  ["Delivered to", "April 18, 2026"],
                  ["Trajectory", tone === "positive" ? "+1.4°C stabilized" : "+2.9°C overshoot"],
                  ["Confidence", tone === "positive" ? "87%" : "62%"],
                ].map(([k, v]) => (
                  <div key={k} className="flex justify-between gap-2 font-mono">
                    <span className="text-muted-foreground">{k}</span>
                    <span>{v}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Letter body */}
            <div className="p-7 sm:p-10 max-h-[560px] overflow-y-auto relative">
              <div className="absolute top-0 inset-x-0 h-12 bg-gradient-to-b from-card to-transparent pointer-events-none" />
              <article className="font-sans text-[15px] leading-[1.85] text-foreground/90 whitespace-pre-wrap">
                {letter.body}
              </article>
              <div className="mt-6 inline-flex items-center gap-2 px-3 py-1.5 rounded-full glass text-xs font-mono">
                <span className={`h-1.5 w-1.5 rounded-full ${tone === "positive" ? "bg-emerald-400" : "bg-rose-400"} animate-pulse`} />
                Signed via temporal cryptography · verified
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
